apiVersion: v1
kind: Service
metadata:
  name: my-python-app
  namespace: my-namespace
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 
  type: ClusterIP
