apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-python-app.fullname" . }}
  labels:
    app: {{ include "my-python-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-python-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-python-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: FLASK_ENV
              value: {{ .Values.env.FLASK_ENV | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}

